#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# the "wild_index" route name is not important yet
wild_show_index:
  path: /wild/
  controller: App\Controller\WildController::index


home_show_index:
  path: /home/
  controller: App\Controller\DefaultController::index
